import { AnalysisResult } from '../types';

/**
 * Generates an executive printable HTML report and triggers browser print or file download
 */
export function downloadHtmlReport(result: AnalysisResult): void {
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Fruit Quality Assessment Report - ${result.id}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #0F172A;
      background: #FFFFFF;
      margin: 0;
      padding: 36px;
      line-height: 1.5;
    }
    .header {
      border-bottom: 2px solid #E2E8F0;
      padding-bottom: 18px;
      margin-bottom: 24px;
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
    }
    .title {
      font-size: 22px;
      font-weight: 700;
      color: #0F172A;
      margin: 0 0 6px 0;
    }
    .subtitle {
      font-size: 13px;
      color: #64748B;
      margin: 0;
    }
    .disclaimer-box {
      background: #F8FAFC;
      border: 1px solid #E2E8F0;
      border-left: 4px solid #3B82F6;
      padding: 12px 16px;
      border-radius: 6px;
      margin-bottom: 24px;
      font-size: 12px;
      color: #475569;
    }
    .meta-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 16px;
      margin-bottom: 28px;
    }
    .meta-card {
      background: #F8FAFC;
      border: 1px solid #E2E8F0;
      border-radius: 8px;
      padding: 12px;
    }
    .meta-label {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #64748B;
      margin-bottom: 4px;
    }
    .meta-value {
      font-size: 16px;
      font-weight: 600;
      color: #0F172A;
    }
    .fruit-table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 16px;
      font-size: 13px;
    }
    .fruit-table th {
      background: #F1F5F9;
      text-align: left;
      padding: 10px 12px;
      font-weight: 600;
      border-bottom: 2px solid #CBD5E1;
      color: #334155;
    }
    .fruit-table td {
      padding: 12px;
      border-bottom: 1px solid #E2E8F0;
      vertical-align: top;
    }
    .badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 600;
    }
    .badge-excellent { background: #DCFCE7; color: #166534; }
    .badge-good { background: #E0F2FE; color: #075985; }
    .badge-fair { background: #FEF3C7; color: #92400E; }
    .badge-poor { background: #FEE2E2; color: #991B1B; }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #E2E8F0;
      font-size: 11px;
      color: #94A3B8;
      display: flex;
      justify-content: space-between;
    }
    @media print {
      body { padding: 0; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1 class="title">Fruit Quality Assessment Report</h1>
      <p class="subtitle">FruitVision DL — Intelligent Vision-Based Assessment System</p>
    </div>
    <div style="text-align: right;">
      <div style="font-size: 13px; font-weight: 600;">Report ID: ${result.id}</div>
      <div style="font-size: 12px; color: #64748B;">Date: ${result.date} ${result.time}</div>
    </div>
  </div>

  <div class="disclaimer-box">
    <strong>Technical Disclosure (AI Honesty Notice):</strong> This evaluation was generated by the Local Browser-Based Demo Engine using HTML5 Canvas image processing heuristics (luminance, color variance, saturation, dark pixel blemish ratio). No remote API calls or external neural networks were invoked. EfficientNet V2 and YOLO models are designated for the planned production backend.
  </div>

  <div class="meta-grid">
    <div class="meta-card">
      <div class="meta-label">Overall Visual Score</div>
      <div class="meta-value">${result.overallQualityScore} / 100</div>
    </div>
    <div class="meta-card">
      <div class="meta-label">Total Fruits Detected</div>
      <div class="meta-value">${result.fruits.length} Items</div>
    </div>
    <div class="meta-card">
      <div class="meta-label">Mode</div>
      <div class="meta-value">${result.mode === 'benchmark' ? 'Benchmark Demo' : 'Local Custom Demo'}</div>
    </div>
    <div class="meta-card">
      <div class="meta-label">Batch Quality</div>
      <div class="meta-value">${result.summary.excellent + result.summary.good >= result.summary.poor ? 'Acceptable' : 'Sub-Standard'}</div>
    </div>
  </div>

  <h2 style="font-size: 16px; margin: 24px 0 8px 0; color: #0F172A;">Individual Item Breakdown</h2>
  <table class="fruit-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Fruit Type</th>
        <th>Classification Mode</th>
        <th>Quality Category</th>
        <th>Visual Score</th>
        <th>Key Analysis Factors</th>
        <th>Recommendation</th>
      </tr>
    </thead>
    <tbody>
      ${result.fruits
        .map(
          (f) => `
        <tr>
          <td><strong>#${f.fruitNumber}</strong></td>
          <td>${(f as any).fruit_type || f.fruitType || 'Unknown/Low Confidence'}</td>
          <td>${f.isUserAssisted ? 'User-Assisted Demo' : 'Benchmark Demo'}</td>
          <td>
            <span class="badge badge-${f.qualityCategory.toLowerCase()}">${f.qualityCategory}</span>
          </td>
          <td><strong>${f.qualityScore}/100</strong></td>
          <td>
            <div style="font-size: 11px; color: #475569;">
              Lum: ${f.factors.brightness}% | Sat: ${f.factors.saturation}% | Dark: ${f.factors.darkRegionProportion}% | Sharp: ${f.factors.sharpness}%
            </div>
          </td>
          <td><div style="max-width: 260px; font-size: 12px;">${f.recommendation}</div></td>
        </tr>
      `
        )
        .join('')}
    </tbody>
  </table>

  <div class="footer">
    <div>Generated offline via FruitVision DL Local Client Engine</div>
    <div>Page 1 of 1</div>
  </div>

  <script>
    window.onload = function() {
      window.print();
    };
  </script>
</body>
</html>`;

  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `fruitvision_report_${result.id}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}

/**
 * Downloads structured JSON of the analysis report
 */
export function downloadJsonReport(result: AnalysisResult): void {
  const jsonString = JSON.stringify(result, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `fruitvision_data_${result.id}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}
